### ISSUE TITLE
RoR group project: set up Kanban board

### ISSUE THREAD

**Issue by Farida-Hamid** [Farida-Hamid/Recipe-App#14]
Dear Code Reviewer, 

In this capstone project, we are two members @Farida-Hamid and @skyv26 and here is the link for our [Kanban Board](https://github.com/users/Farida-Hamid/projects/10).

**Comment by mirouhml** [comment]
# APPROVED 🟢

Hi @Farida-Hamid @skyv26, 

Your Kanban board is complete!  There is nothing else to say other than... it's time to start the project :shipit: 
Congratulations and good luck with your group project! 🎉 

![](https://media1.giphy.com/media/ZdUnQS4AXEl1AERdil/giphy.gif?cid=ecf05e471p9juygtcaesd615kgxa3b2n2dt6xyrzcycnk4b3&rid=giphy.gif&ct=g)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by skyv26** [comment]
### @mirouhml Thank you very much ❤️ 
### Happy Coding 🥂
