### ISSUE TITLE
[ 2pt ] - Group Task

### ISSUE THREAD

**Issue by Farida-Hamid** [Farida-Hamid/Recipe-App#2]
# Group Task #2 - Recipe App Model [ 2pt ]

- Make sure the project is created with `PostgreSQL`.
- Build your project schema.
   - Create and run the necessary migration files.
   - Table and column names should match the ERD diagram.
   - Foreign keys should be included.
   - All columns that are foreign keys should have a corresponding index.

**Comment by skyv26** [comment]
## Successfully Completed the Task.
